hw_project10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
]

quotes/urls.py
from django.urls import path
from .views import (
    AddAuthorView,
    AddQuoteView,
    TagDetailView,
    AuthorDetailView,
)
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    # path("tag/<slug:tag_slug>/", TagDetailView.as_view(), name="tag_detail"),
    path("add_quote/", AddQuoteView.as_view(), name="add_quote"),
    path("add_author/", AddAuthorView.as_view(), name="add_author"),
    path("author/<str:pk>/", AuthorDetailView.as_view(), name="author"),
    path("quote_list/<str:name>/", TagDetailView.as_view(), name="quote_list"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
]

quotes/models.py
from django.db import models
# from django.utils.text import slugify


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=255)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

users/models.py
# users/models.py
from django.db import models

quotes/forms.py
from django import forms
from .models import Author, Tag, Quote


class AddQuoteForm(forms.Form):
    quote = forms.CharField(label="Quote", widget=forms.Textarea)
    author = forms.CharField(label="Author")
    tags = forms.CharField(label="Tags", help_text="Separate tags with commas")


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ["quote", "tags", "author"]


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name"]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User



class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput())

    password1 = forms.CharField(
        max_length=50, required=True, widget=forms.PasswordInput())
    password2 = forms.CharField(
        max_length=50, required=True, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]

quotes/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.http import Http404
from django.views import View
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .utils import get_mongodb
from .forms import AddQuoteForm, AuthorForm, QuoteForm
from bson.objectid import ObjectId
from .models import Tag


def main(request, page=1):
    per_page = 10
    template_name = "quotes/index.html"
    db = get_mongodb()
    quotes = db.quoters.find()
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(
        request,
        template_name,
        context={"quotes": quotes_on_page, "paginator": paginator},
    )


# class QuoteListView(View):
#     template_name = "quotes/index.html"
#     per_page = 10

#     def get(self, request, page=1):
#         db = get_mongodb()
#         quotes = db.quoters.find()
#         paginator = Paginator(list(quotes), self.per_page)
#         quotes_on_page = paginator.page(page)
#         return render(
#             request,
#             self.template_name,
#             context={"quotes": quotes_on_page, "paginator": paginator},
#         )


class AuthorDetailView(View):
    template_name = "quotes/author.html"

    def get(self, request, pk: str):
        db = get_mongodb()
        author = db.authors.find_one({"_id": ObjectId(pk)})
        print(author)
        return render(request, self.template_name, context={"author": author})


class AddAuthorView(CreateView):
    template_name = "quotes/add_author.html"
    form_class = AuthorForm
    success_url = reverse_lazy("quotes:quote_list")


class TagDetailView(View):
    template_name = "quotes/quote_list .html"

    def get(self, request, name: str):
        db = get_mongodb()
        quotes = list(db.quoters.find({"tags": name}))
        context = {"tag": name, "quotes": quotes}
        return render(request, self.template_name, context)


class AddQuoteView(CreateView):
    template_name = "quotes/add_quote.html"
    form_class = QuoteForm
    success_url = reverse_lazy("quotes:quote_list")

    def get(self, request):
        form = AddQuoteForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = AddQuoteForm(request.POST)
        if form.is_valid():
            return redirect("quotes:quote_list")
        return render(request, self.template_name, {"form": form})

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import RegisterForm, LoginForm


def signupuser(request): 
    if request.user.is_authenticated:
        return redirect(to="quotes:root")

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:root")
        else:
            return render(request, "users/signup.html", context={"form": form})

    return render(request, "users/signup.html", context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to="quotes:root")

    if request.method == "POST":
        user = authenticate(
            username=request.POST["username"], password=request.POST["password"]
        )
        if user is None:
            messages.error(request, "Username or password didn't match")
            return redirect(to="users:login")

        login(request, user)
        return redirect(to="quotes:root")

    return render(request, "users/login.html", context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to="quotes:root")

quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}

{% block title %}Add author - Quotes{% endblock %}

{% block content %}
<div style="width: 50%; margin: auto; text-align: center; font-family: 'Raleway';font-size: large;">
    <h2 style="color: green; margin-bottom: 50px;">ADD AUTHOR</h2>
    <form method="post" action="{% url 'quotes:add_author' %}" style="display: inline-block; text-align: left;">
        {% csrf_token %}
        <div style="margin-bottom: 10px;">
            <label for="{{ form.fullname.id_for_label }}" style="margin-right: 50px;">{{ form.fullname.label }}</label>
            {{ form.fullname }}
        </div>
        <div style="margin-bottom: 10px;">
            <label for="{{ form.born_date.id_for_label }}" style="margin-right: 50px;">{{ form.born_date.label }}</label>
            {{ form.born_date }}
        </div>
        <div style="margin-bottom: 10px;">
            <label for="{{ form.born_location.id_for_label }}" style="margin-right: 25px;">{{ form.born_location.label }}</label>
            {{ form.born_location }}
        </div>
        <div style="margin-bottom: 30px; ">
            <label for="{{ form.description.id_for_label }}" style="margin-right: 40px;">{{ form.description.label }}</label>
            {{ form.description }}
        </div>
        <button type="submit" style="margin-top: 10px; float: right; "class="btn btn-success">  Save  </button>
    </form>
</div>
{% endblock %}

quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}

{% block title %}Add quote - Quotes{% endblock %}

{% block content %}

<div style="width: 50%; margin: auto; text-align: center; font-family: 'Raleway';font-size: large;">
    <h2 style="color: green; margin-bottom: 50px;">ADD QUOTE</h2>
    <form method="post" action="{% url 'quotes:add_quote' %}" style="display: inline-block; text-align: left;">
        {% csrf_token %}
        <div style="margin-bottom: 10px;">
            <label for="{{ form.quote.id_for_label }}" style="margin-right: 50px;">{{ form.quote.label }}</label>
            {{ form.quote }}
        </div>
        <div style="margin-bottom: 10px;">
            <label for="{{ form.tags.id_for_label }}" style="margin-right: 60px;">{{ form.tags.label}}</label>
            {{ form.tags }}
        </div>
        <div style="margin-bottom: 30px; ">
            <label for="{{ form.author.id_for_label }}" style="margin-right: 40px;">{{ form.author.label}}</label>
            {{ form.author }}
        </div>
        <button type="submit" style="margin-top: 10px; float: right; "class="btn btn-success"> Save
        </button>
    </form>
</div>
{% endblock %}

quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block title %}{{ author.fullname }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <h2 style="color: green; text-align: center;">{{ author.fullname }}</h2>
        <p><strong style="color: green;">Date of birth:</strong> {{ author.born_date }}</p>
        <p><strong style="color: green;">Birthplace:</strong> {{ author.born_location }}</p>
        <p><strong style="color: green;">Description:</strong> {{ author.description }}</p>
    </div>
</div>
{% endblock %}

quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>

<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="color: green; text-decoration: none">Quotes</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:logout' %}" class="btn btn-success">Logout</a>
                    {% else %}
                    <a href="{% url 'users:signup' %}" class="btn btn-success">SignUp</a>
                    <a href="{% url 'users:login' %}" class="btn btn-success">Login</a>
                    {% endif %}
                </p>
            </div>
        </div>

        {% block content %} {% endblock %}

    </div>
</body>

</html>

quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{ quote.quote }}
            </span>
            <span>by <small class="author" itemprop="author">{{ quote.author|author }}</small>
                <a href="{% url 'quotes:author' pk=quote.author %}" style="color: green;">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="{% url 'quotes:quote_list' name=tag%}">{{ tag }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
            {% if user.is_authenticated %}
            <a href="{% url 'quotes:add_author' %}" class="btn btn-success">Add author</a>
            <a href="{% url 'quotes:add_quote' %}" class="btn btn-success">Add quote</a>
            {% endif %}
        <nav>
            <ul class="pager" >
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}" 
                        href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}" style="color: green;">
                        <span aria-hidden="true">

                        </span> Previous
                        </a>
                    </li>
            
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}" 
                        href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}" style="color: green;">
                        Next <span aria-hidden="true">

                        </span></a>
                    </li>

            </ul>
        </nav>
    </div>

</div>

{% endblock %}

quotes/templates/quotes/quote_list .html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<h2 style="color: green; text-align: center;">List quotes</h2>
<h2 style="color: green; font-family:'Raleway'; font-size: large; "> Tag - {{ tag }}</h2>
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
            {% if tag in quote.tags %}
                <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                    <span class="text" itemprop="text">
                        {{ quote.quote }}
                    </span>
                    <span>by <small class="author" itemprop="author">{{ quote.author|author }}</small>
                        <a href="{% url 'quotes:author' pk=quote.author %}">(about)</a>
                    </span>
                
                </div>
            {% endif %}

        {% endfor %}
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
<div >
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div style="color: green; margin-top: 10px; margin-bottom: 50px; text-align: center; font-family: 'Raleway';font-size: large;" >
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div style="color: green; margin-bottom: 50px; text-align: center; font-family: 'Raleway';font-size: large;" >
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit" style="margin-left: 50%; "  class="btn btn-success" >Submit</button>
        <button type="reset"  class="btn btn-success">Reset</button>
    </div>
</form>

{% endblock %}

users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2 style="color: green;text-align: center; font-family: 'Raleway';">Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}" style="color: green; margin-top: 20px; margin-bottom: 50px; text-align: center; font-family: 'Raleway';font-size: large;">
    {% csrf_token %}
    <div style=" margin-top: 10px;">
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div style=" margin-top: 10px;">
        <label> Enter the password:   
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div style=" margin-top: 10px;margin-bottom: 50px;">
        <label> Сonfirm password:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit" style="margin-left: 20%;" class="btn btn-success">Submit</button>
        <button type="reset" class="btn btn-success">Reset</button>
    </div>
</form>

{% endblock %}